# Generated by Django 3.0.2 on 2020-02-10 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweets',
            name='location',
        ),
        migrations.AlterField(
            model_name='tweets',
            name='id',
            field=models.IntegerField(default='NA', primary_key=True, serialize=False),
        ),
    ]
