# Generated by Django 3.0.4 on 2020-03-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='coordinates',
            field=models.CharField(default='NA', max_length=200, null=True),
        ),
    ]
