# Generated by Django 3.0.2 on 2020-02-28 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default='NA', null=True)),
                ('date', models.DateTimeField(default='2012-09-04 06:00:00', null=True)),
            ],
        ),
    ]
