# Generated by Django 3.0.2 on 2020-02-11 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20200210_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='date',
            field=models.IntegerField(default='NA', max_length=200),
        ),
    ]
