# Generated by Django 3.0.2 on 2020-03-03 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_tweetcount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TweetCount',
            new_name='TweetsCount',
        ),
    ]
