# Generated by Django 3.0.4 on 2020-03-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_tweets_coordinates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweets',
            old_name='coordinates',
            new_name='coordinates_lat',
        ),
        migrations.AddField(
            model_name='tweets',
            name='coordinates_lon',
            field=models.CharField(default='NA', max_length=200, null=True),
        ),
    ]
