# Generated by Django 3.0.2 on 2020-02-16 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200211_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='location',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='date',
            field=models.DateField(default='NA', max_length=200),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
