# Generated by Django 3.0.2 on 2020-02-16 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20200216_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
