# Generated by Django 3.0.2 on 2020-02-16 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20200216_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='date',
            field=models.DateField(default='NA', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='followers',
            field=models.CharField(default='NA', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='location',
            field=models.CharField(default='NA', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='tweetText',
            field=models.CharField(default='NA', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='user',
            field=models.CharField(default='NA', max_length=200, null=True),
        ),
    ]
