# Generated by Django 3.0.2 on 2020-02-16 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20200216_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='followers',
            field=models.IntegerField(default='NA', null=True),
        ),
    ]
