# Generated by Django 3.0.2 on 2020-02-16 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20200216_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='date',
            field=models.DateTimeField(default='NA', max_length=200, null=True),
        ),
    ]
