# Generated by Django 3.0.2 on 2020-02-16 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20200216_0327'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default='NA', null=True)),
            ],
        ),
    ]
