# Generated by Django 3.0.2 on 2020-02-25 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_auto_20200225_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetcount',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
