# Generated by Django 3.0.2 on 2020-02-25 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_auto_20200225_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetcount',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
